import { useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const api = import.meta.env.VITE_API_URL ?? "http://localhost:4000";
type Job = { id: string; ticketNo: string; customerName: string; phone: string; product: string; brand?: string; complaint: string; status: string; estimatedAmount?: number };
function App() {
  const [jobs, setJobs] = useState<Job[]>([]); const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ customerName:"", phone:"", category:"MOBILE", product:"", brand:"", model:"", imei1:"", complaint:"", estimatedAmount:"" });
  const update = (key: string, value: string) => setForm({ ...form, [key]: value });
  const load = async () => { const res = await fetch(`${api}/api/repair-jobs`); setJobs(await res.json()); };
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setNotice(""); const res = await fetch(`${api}/api/repair-jobs`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({...form, quantity:1, estimatedAmount: form.estimatedAmount ? Number(form.estimatedAmount) : undefined}) }); if (!res.ok) return setNotice("कृपया सभी जरूरी जानकारी भरें।"); setNotice("Repair job सफलतापूर्वक बन गया।"); setForm({ customerName:"", phone:"", category:"MOBILE", product:"", brand:"", model:"", imei1:"", complaint:"", estimatedAmount:"" }); load(); };
  return <main><header><div><small>FIXMITRA</small><h1>Repair Desk</h1></div><button onClick={load}>Refresh Jobs</button></header><section className="stats"><article><b>{jobs.length}</b><span>Open Jobs</span></article><article><b>{jobs.filter(j=>j.status === "READY").length}</b><span>Ready for Delivery</span></article><article><b>₹{jobs.reduce((a,j)=>a+(j.estimatedAmount||0),0).toLocaleString("en-IN")}</b><span>Estimated Value</span></article></section><div className="grid"><section className="panel"><h2>नया Repair Job</h2><p className="muted">Customer और device की entry करें।</p><form onSubmit={submit}><input required placeholder="Customer Name *" value={form.customerName} onChange={e=>update("customerName",e.target.value)}/><input required placeholder="Mobile Number *" value={form.phone} onChange={e=>update("phone",e.target.value)}/><select value={form.category} onChange={e=>update("category",e.target.value)}><option value="MOBILE">Mobile Repair</option><option value="ELECTRONICS">Electronics Repair</option></select><input required placeholder="Product * (e.g. Phone, TV)" value={form.product} onChange={e=>update("product",e.target.value)}/><input placeholder="Brand" value={form.brand} onChange={e=>update("brand",e.target.value)}/><input placeholder="Model" value={form.model} onChange={e=>update("model",e.target.value)}/><input placeholder="IMEI / Serial Number" value={form.imei1} onChange={e=>update("imei1",e.target.value)}/><textarea required placeholder="Problem Description *" value={form.complaint} onChange={e=>update("complaint",e.target.value)}/><input type="number" min="0" placeholder="Estimated Amount" value={form.estimatedAmount} onChange={e=>update("estimatedAmount",e.target.value)}/><button className="primary">Create Job Card</button>{notice && <p className="notice">{notice}</p>}</form></section><section className="panel"><h2>Repair Queue</h2>{jobs.length === 0 ? <p className="muted">अभी कोई repair job नहीं है।</p> : <div className="jobs">{jobs.map(job=><article className="job" key={job.id}><div><b>{job.ticketNo}</b><p>{job.customerName} · {job.phone}</p><p>{job.brand} {job.product} · {job.complaint}</p></div><span>{job.status.replaceAll("_"," ")}</span></article>)}</div>}</section></div></main>;
}
createRoot(document.getElementById("root")!).render(<App/>);
