import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import "./auth.css";

const api = import.meta.env.VITE_API_URL ?? "http://localhost:4000";
type Job = { id:string; ticket_no:string; customer_name:string; phone:string; product:string; brand?:string; complaint:string; status:string; estimated_amount?:number };
type Auth = { token:string; user:{ role:string } };
const emptyJob={customerName:"",phone:"",category:"MOBILE",product:"",brand:"",model:"",imei1:"",complaint:"",estimatedAmount:""};

function App() {
  const [auth,setAuth]=useState<Auth|null>(()=>{const saved=localStorage.getItem("fixmitra_auth"); return saved?JSON.parse(saved):null});
  const [mode,setMode]=useState<"login"|"setup">("login"); const [message,setMessage]=useState("");
  const [login,setLogin]=useState({slug:"",phone:"",password:""}); const [setup,setSetup]=useState({businessName:"",slug:"",ownerName:"",phone:"",password:""});
  const [jobs,setJobs]=useState<Job[]>([]); const [job,setJob]=useState(emptyJob);
  const request=async(path:string, options:RequestInit={})=>fetch(`${api}${path}`,{...options,headers:{"Content-Type":"application/json",...(auth?{Authorization:`Bearer ${auth.token}`}:{}) ,...(options.headers||{})}});
  const saveAuth=(data:Auth)=>{localStorage.setItem("fixmitra_auth",JSON.stringify(data));setAuth(data);};
  const load=async()=>{if(!auth)return; const res=await request("/api/repair-jobs"); if(res.ok)setJobs(await res.json()); else if(res.status===401)logout();};
  useEffect(()=>{load();},[auth?.token]);
  const submitLogin=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const res=await request("/api/auth/login",{method:"POST",body:JSON.stringify(login)});const data=await res.json();if(!res.ok)return setMessage(data.message||"Login failed.");saveAuth(data);};
  const submitSetup=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const res=await request("/api/setup/owner",{method:"POST",body:JSON.stringify(setup)});const data=await res.json();if(!res.ok)return setMessage(data.message||"Setup failed.");saveAuth(data);};
  const submitJob=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const res=await request("/api/repair-jobs",{method:"POST",body:JSON.stringify({...job,quantity:1,estimatedAmount:job.estimatedAmount?Number(job.estimatedAmount):undefined})});const data=await res.json();if(!res.ok)return setMessage(data.message||"Repair job could not be created.");setMessage(`Job card ${data.ticket_no} बन गया।`);setJob(emptyJob);load();};
  const logout=()=>{localStorage.removeItem("fixmitra_auth");setAuth(null);setJobs([]);};
  const setValue=<T extends Record<string,string>>(setter:React.Dispatch<React.SetStateAction<T>>,key:keyof T,value:string)=>setter((current)=>({...current,[key]:value}));
  const setAuthField=(key:"slug"|"phone"|"password",value:string)=>mode==="login"?setLogin(current=>({...current,[key]:value})):setSetup(current=>({...current,[key]:value}));
  if(!auth) return <main className="auth-page"><section className="auth-card"><small>FIXMITRA</small><h1>{mode==="login"?"Welcome back":"अपनी दुकान शुरू करें"}</h1><p className="muted">Repair, sales और service का आपका डिजिटल साथी।</p><form onSubmit={mode==="login"?submitLogin:submitSetup}>{mode==="setup"&&<><input required placeholder="Business / Shop Name" value={setup.businessName} onChange={e=>setValue(setSetup,"businessName",e.target.value)}/><input required placeholder="Owner Name" value={setup.ownerName} onChange={e=>setValue(setSetup,"ownerName",e.target.value)}/></>}<input required placeholder="Business ID (e.g. taj-electronics)" value={mode==="login"?login.slug:setup.slug} onChange={e=>setAuthField("slug",e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))}/><input required placeholder="Mobile Number" inputMode="numeric" value={mode==="login"?login.phone:setup.phone} onChange={e=>setAuthField("phone",e.target.value)}/><input required type="password" minLength={8} placeholder="Password (minimum 8 characters)" value={mode==="login"?login.password:setup.password} onChange={e=>setAuthField("password",e.target.value)}/><button className="primary">{mode==="login"?"Login करें":"Create Owner Account"}</button>{message&&<p className="notice">{message}</p>}</form><button className="text-button" onClick={()=>{setMode(mode==="login"?"setup":"login");setMessage("");}}>{mode==="login"?"नई दुकान है? Owner account बनाएं":"पहले से account है? Login करें"}</button></section></main>;
  return <main><header><div><small>FIXMITRA</small><h1>Repair Desk</h1></div><div className="header-actions"><span className="role">{auth.user.role}</span><button onClick={load}>Refresh</button><button onClick={logout}>Logout</button></div></header><section className="stats"><article><b>{jobs.filter(j=>j.status!=="DELIVERED").length}</b><span>Open Jobs</span></article><article><b>{jobs.filter(j=>j.status === "READY").length}</b><span>Ready for Delivery</span></article><article><b>₹{jobs.reduce((a,j)=>a+Number(j.estimated_amount||0),0).toLocaleString("en-IN")}</b><span>Estimated Value</span></article></section><div className="grid"><section className="panel"><h2>नया Repair Job</h2><p className="muted">Customer और device की entry करें।</p><form onSubmit={submitJob}><input required placeholder="Customer Name *" value={job.customerName} onChange={e=>setValue(setJob,"customerName",e.target.value)}/><input required placeholder="Mobile Number *" value={job.phone} onChange={e=>setValue(setJob,"phone",e.target.value)}/><select value={job.category} onChange={e=>setValue(setJob,"category",e.target.value)}><option value="MOBILE">Mobile Repair</option><option value="ELECTRONICS">Electronics Repair</option></select><input required placeholder="Product * (e.g. Phone, TV)" value={job.product} onChange={e=>setValue(setJob,"product",e.target.value)}/><input placeholder="Brand" value={job.brand} onChange={e=>setValue(setJob,"brand",e.target.value)}/><input placeholder="Model" value={job.model} onChange={e=>setValue(setJob,"model",e.target.value)}/><input placeholder="IMEI / Serial Number" value={job.imei1} onChange={e=>setValue(setJob,"imei1",e.target.value)}/><textarea required placeholder="Problem Description *" value={job.complaint} onChange={e=>setValue(setJob,"complaint",e.target.value)}/><input type="number" min="0" placeholder="Estimated Amount" value={job.estimatedAmount} onChange={e=>setValue(setJob,"estimatedAmount",e.target.value)}/><button className="primary">Create Job Card</button>{message&&<p className="notice">{message}</p>}</form></section><section className="panel"><h2>Repair Queue</h2>{jobs.length===0?<p className="muted">अभी कोई repair job नहीं है।</p>:<div className="jobs">{jobs.map(item=><article className="job" key={item.id}><div><b>{item.ticket_no}</b><p>{item.customer_name} · {item.phone}</p><p>{item.brand} {item.product} · {item.complaint}</p></div><span>{item.status.replaceAll("_"," ")}</span></article>)}</div>}</section></div></main>;
}
createRoot(document.getElementById("root")!).render(<App/>);
